stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - echo "Compiling source code..."
    - make

test-job:
  stage: test
  script:
    - echo "Running tests..."
    - make test

deploy-job:
  stage: deploy
  script:
    - echo "Deploying application..."
    - ./deploy.sh
  only:
    - main   # Only run deploy on main branch
